version: '3.9'

services:
  db:
    platform: '${PLATFORM}'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DATABASE_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    container_name: db
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    expose:
      # Opens port 3306 on the container
      - '${DATABASE_PORT}'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: backend
    volumes:
      - ./backend/src:/home/node/backend/src
      - ./backend/nodemon.json:/home/node/backend/nodemon.json
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/home/node/frontend
      - /home/node/frontend/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
# Names our volume
volumes:
  my-db:
