version: '3.9'

services:
  db:
    platform: '${PLATFORM}'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DATABASE_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    expose:
      # Opens port 3306 on the container
      - '${DATABASE_PORT}'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
# Names our volume
volumes:
  my-db:
